# Generated by Django 4.2.30 on 2026-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_categoria_proyecto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='tecnolgia',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, null=True, related_name='proyectos', to='website.tecnologia'),
        ),
    ]
